# Estudo do NUMPY
### Exemplos extraídos do livro PYTHON - para analise de dados de Wes McKinney (Criador do Pandas)

In [1]:
# Importação

import numpy as np

rng = np.random.default_rng(seed=12345)

## Array

O array no Numpy tem uma melhor performance do que estruturas nativas do Python como uma lista

O array Numpy, pode ter várias dimensões, e tem propriedades como:
* shape
* dtype

No Numpay temo o {arange()} similar ao range() do python, com a diferença que este retorna um array unidimensional

Definições:\
Array unidimensional:   Vetor\
Array bidimensional:    Tabela


In [2]:
array_teste = np.arange(5)
array_teste

array([0, 1, 2, 3, 4])

In [3]:
print(type(array_teste))

<class 'numpy.ndarray'>


### Dimensões

A propriedadw [ ndim ] informa as dimensões de um array

##### Vetor

In [4]:
vetor = np.array([0,1,2,3,4])
print(vetor)

#Dimensões
print(f"Dimensões [{vetor.ndim}]")

[0 1 2 3 4]
Dimensões [1]


##### Matriz

In [5]:
tabela = np.array([[1,2,3],[4,5,6]])
print(tabela)

#Dimensões
print(f"Dimensões [{tabela.ndim}]")

[[1 2 3]
 [4 5 6]]
Dimensões [2]


##### Tri dimensional (cubo)

In [6]:
tabela_3d = np.array([
    [#Linha 0
        #coluna 0
        #p0, p1, p2
        [1,2,3] 
        #coluna 1
        #p0, p1, p2
        ,[4,5,6]
        #coluna 2
        #p0, p1, p2
        ,[7,8,9]
    ]
    ,[#Linha 1
        #coluna 0
        #p0, p1, p2
        [10,11,12]
        #coluna 1
        #p0, p1, p2
        ,[13,14,15]
        #coluna 2
        #p0, p1, p2
        ,[16,17,18]
    ]
])
print(tabela_3d)

#Dimensões
print(f"Dimensões [{tabela_3d.ndim}]")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Dimensões [3]


In [7]:
print(tabela_3d[0])
print(tabela_3d[0,0])
print(tabela_3d[0,0,0])

print(tabela_3d[0,0,0])
print(tabela_3d[0,1,0])
print(tabela_3d[0,2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1
1
4
7


### Forma (Shape)

In [8]:
print(vetor.shape)
print(tabela.shape)
print(tabela_3d.shape)

(5,)
(2, 3)
(2, 3, 3)


## Tipo de dados

Um array Numpy é homogeneo, ou seja possui um tipo de dado para todos os elementos.

*** Case ele seja númerico, e acrescente um valor STRING ele será convertido para string

In [9]:
vetor_2 = np.array([0,1,2])

print(vetor_2)
print(vetor_2.dtype)

vetor_2 = np.array([0,1,'2'])

print(vetor_2)
print(vetor_2.dtype)

[0 1 2]
int32
['0' '1' '2']
<U11


##### Definindo o tipo de dado

In [10]:
dtype_array = np.array([0,1,2,3],dtype=np.int32)
print(dtype_array)

dtype_array = np.array([0,1,2,3],dtype=np.float32)
print(dtype_array)

dtype_array = np.array([0,1,2,3],dtype=np.unicode_)
print(dtype_array)

[0 1 2 3]
[0. 1. 2. 3.]
['0' '1' '2' '3']


##### Casting - Alterando o tipo de dado

In [11]:
dtype_cast_array = np.array([0,1,2,3])
print(dtype_cast_array.dtype)
print(dtype_cast_array)

dtype_cast_array = dtype_cast_array.astype(np.float32)
print(dtype_cast_array.dtype)
print(dtype_cast_array)

dtype_cast_array = dtype_cast_array.astype(np.string_)
print(dtype_cast_array.dtype)
print(dtype_cast_array)

dtype_cast_array = dtype_cast_array.astype(np.unicode_)
print(dtype_cast_array.dtype)
print(dtype_cast_array)

dtype_cast_array = dtype_cast_array.astype(np.float32)
print(dtype_cast_array.dtype)
print(dtype_cast_array)

dtype_cast_array = dtype_cast_array.astype(np.int32)
print(dtype_cast_array.dtype)
print(dtype_cast_array)

int32
[0 1 2 3]
float32
[0. 1. 2. 3.]
|S32
[b'0.0' b'1.0' b'2.0' b'3.0']
<U32
['0.0' '1.0' '2.0' '3.0']
float32
[0. 1. 2. 3.]
int32
[0 1 2 3]


## Aritmetica dos array Numpy

###### Operações

Os array Numpy suportam operações matemática sem necessidade de loops e eles propagam o calculo para cada elemento do array

In [12]:
aritmetica = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(aritmetica)

# Operações com valores escalares propagam para todos os valores do array

# SOMA
print("soma")
result = aritmetica + 10
print(result)

print("\nsoma")
# SOMA COM ARRAY DO MESMO TAMANHO
result = aritmetica + result
print(result)

print("subtração")
# SUBTRAÇÃO
result = aritmetica - 2
print(result)

print("\nmultiplicação")
# MULTIPLICAÇÃO
result = aritmetica * aritmetica
print(result)

print("\ndivisão")
# DIVISÃO
result = aritmetica / 2
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
soma
[[11 12 13]
 [14 15 16]
 [17 18 19]]

soma
[[12 14 16]
 [18 20 22]
 [24 26 28]]
subtração
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

multiplicação
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

divisão
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


## Indexação e fatiamento básicos

Os array Numpy suportam a indexação pela notação de colchetes ( [ ] ), e o fatiamento, informando o inicio e fim do trecho selecionado, onde o primeiro parametro é o INDICE, o segundo é a contagem, e o terceiro é step.

ex:

INDICE:             0   ,1      ,2      ,3      ,4  
array = np.array([  'A' ,'B'    ,'C'    ,'D'   ,'E' ])\
CONTAGEM            1   ,2      ,3      ,4      ,5  

A atribuição de valores é feita diretamente no array ORIGINAL e não em um cópia como acontece com as listas python.

Outro recurso interessante é o BROADCAST que ocorre quando é atribuido um valor em um slice.

### Indexação

In [ ]:
array_slice = np.array([[0,1,2,3,4]
                        ,[5,6,7,8,9]
                        ,[10,11,12,13,14]
                        ,[15,16,17,18,19]
                        ,[20,21,22,23,24]])

# Indice
print(f"array_slice: {array_slice}")

# linha 1
print(f"array_slice[0]: {array_slice[0]}")

# linha 3
print(f"array_slice[3]: {array_slice[3]}")

# linha 2 coluna 3
print(f"array_slice[1,2]: {array_slice[1,2]}")

array_slice: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
array_slice[0]: [0 1 2 3 4]
array_slice[3]: [15 16 17 18 19]
array_slice[1,2]: 7
array_slice[1,2]: [ 2  7 12 17 22]


### Fatiamento

In [ ]:
print("\n slices \n")
print(f"array_slice[1]: {array_slice[1]}")
print(f"array_slice[3]: {array_slice[3]}")
print(f"array_slice[4]: {array_slice[4]}")

print(f"array_slice[1]: {array_slice[1:2]}")
print(f"array_slice[3]: {array_slice[3:5]}")

print(f"array_slice[1]: {array_slice[1:2][0,2:4]}")

# BROADCAST

array_slice[1:2][0,2:4] = 100
print(array_slice)

# Mesmo em valores fatiado, eles ainda pertencem ao array original, e caso recebam valores, refletirá no array origem
arr1 = array_slice[0]
print(f"array_slice[0]: {arr1}")

# NÃO altera dos valores do array, ALTERA a variavel substituindo o array
arr1 = 64

print(f"array_slice: {array_slice}")

# SIM altera dos valores do array, PORQUE estamos setando o valor no SLICE
arr1 = array_slice[0]
arr1[:] = 64

print(f"array_slice[0]: {array_slice}")



 slices 

array_slice[1]: [  5   6 100 100   9]
array_slice[3]: [15 16 17 18 19]
array_slice[4]: [20 21 22 23 24]
array_slice[1]: [[  5   6 100 100   9]]
array_slice[3]: [[15 16 17 18 19]
 [20 21 22 23 24]]
array_slice[1]: [100 100]
[[ 64  64  64  64  64]
 [  5   6 100 100   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
array_slice[0]: [64 64 64 64 64]
array_slice: [[ 64  64  64  64  64]
 [  5   6 100 100   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
array_slice[0]: [[ 64  64  64  64  64]
 [  5   6 100 100   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
PRINT linha 3 de array_slice: [[ 64  64  64  64  64]
 [  5   6 100 100   9]
 [ 10  11  12  13  14]]
PRINT linhas depois de 3 de array_slice: [[15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
print(f"PRINT array_slice: {array_slice}")

#  SLICE ATÉ
# linha 3
print(f"PRINT linha 3 de array_slice: {array_slice[:3]}")


#  SLICE ACIMA DE 
# linhas depois de 3
print(f"PRINT linhas depois de 3 de array_slice: {array_slice[3:]}")

#  SLICE ATÉ e ACIMA DE 
# linhas até 2 e colunas depois de 3
print(f"PRINT linhas depois de 3 de array_slice: {array_slice[:2,3:]}")

PRINT array_slice: [[ 64  64  64  64  64]
 [  5   6 100 100   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
PRINT linha 3 de array_slice: [[ 64  64  64  64  64]
 [  5   6 100 100   9]
 [ 10  11  12  13  14]]
PRINT linhas depois de 3 de array_slice: [[15 16 17 18 19]
 [20 21 22 23 24]]
PRINT linhas depois de 3 de array_slice: [[ 64  64]
 [100   9]]


### Indexação booleana

Quando utilizamos um array BOOLEANO para INDEXAR quais as entradas de outros array nós queremos

##### Utilizando operadores de COMPARAÇÃO para gerar arrays BOLEANOS

In [13]:
# Quando utilizamos OPERADORES MATEMATICOS, as aplicações são atribuidas em todos os elementos
# Ex:

pares = np.array([2,4,6])
impares = pares + 1

print(f"pares {pares}")
print(f"impares {impares}")

# Quando utilizamos OPERADORES DE COMPARAÇÃO, as aplicações são atribuidas em todos os elementos mas com VALORES BOLEANOS
# Ex:
num = np.array([1,2,3,4,5,6])
num_bool = (num % 2) == 0

print(f"array num {num}")
print(f"array num considerando que PARES são TRUE e IMPARS são FALSE {num_bool}")


pares [2 4 6]
impares [3 5 7]
array num [1 2 3 4 5 6]
array num considerando que PARES são TRUE e IMPARS são FALSE [False  True False  True False  True]


##### Utilizando ARRAY BOOLEANOS COMO FILTRO

In [23]:

# Exemplo 1 de FILTRO COM DADOS BOOLEANOS
# Array nomes
nomes = np.array(["Paulo", "Lucas","Paulo", "Pietro", "Amanda", "Bianca", "Paulo"])
notas = np.array([[10,0.2],[5,7.5],[8,9],[10,5.5],[2,10],[1,9],[7,9]])

print(f"A notas do Paulo { notas[nomes == 'Paulo']}")

# Exemplo 2 de FILTRO COM DADOS BOOLEANOS

# Atribui um valor BOOLEANO para cada valor array bidimensional (7,2)
cond = notas > 5
print(f"\nNotas > 5 TRUE senão FALSE\n{cond}")

# Atribui um valor BOOLEANO para linha comparando as 2 colunas, resultado em um array unidimensional (7)
cond = cond[:,0] & cond[:,1]
print(f"\nQuem teve as 2 notas maiores que 5 TRUE senão FALSE\n{cond}")

print(f"\nAlunos e notas respectivamente \n{nomes[cond]} \n {notas[cond]}")



A notas do Paulo [[10.   0.2]
 [ 8.   9. ]
 [ 7.   9. ]]

Notas > 5 TRUE senão FALSE
[[ True False]
 [False  True]
 [ True  True]
 [ True  True]
 [False  True]
 [False  True]
 [ True  True]]

Quem teve as 2 notas maiores que 5 TRUE senão FALSE
[False False  True  True False False  True]

Alunos e notas respectivamente 
['Paulo' 'Pietro' 'Paulo'] 
 [[ 8.   9. ]
 [10.   5.5]
 [ 7.   9. ]]


### Indexação sofisticada

Quando utilizamos um array com os a ordem dos indices que queremos selecionar do ARRAY ORIGEM.
Esta ação sempre gera um array, não alterando a estruta do original

In [ ]:
arr = np.zeros((8,4))

for i in range(8):
    arr[i] = i

# Array de SELEÇÃO 1
filtro = [5,2,7]

print(f"Array após SELEÇÃO 1: \n{arr[filtro]}")

# Array de SELEÇÃO 2
filtro = [1,3]

print(f"\nArray após SELEÇÃO 2: \n{arr[filtro]}")

Array após SELEÇÃO 1 
[[5. 5. 5. 5.]
 [2. 2. 2. 2.]
 [7. 7. 7. 7.]]

Array após SELEÇÃO 2 
[[1. 1. 1. 1.]
 [3. 3. 3. 3.]]


## Transposição de arrays e troca de eixos

É o rearranjo do array invertendo linhas em colunas sem fazer uma cópia dos dados

In [16]:
arr = np.arange(15).reshape((3,5))

print(f"array original:\n{arr}")

print(f"\narray transposto:\n{arr.T}")

array original:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

array transposto:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Lógica condicional como operação com arrays

##### Exemplo Obsoleto - Não perfomatico

In [ ]:
# Lógica condicional com LIST COMPREHENSION

xarr = np.array([1.1,1.2,1.3,1.4,1.5])

yarr = np.array([2.1,2.2,2.3,2.4,2.5])

cond = np.array([True,False,True,True,False])

# Com base nos valores booleanos do array COND é definido o resultado
result = [x if c else y for x,y,c in zip(xarr,yarr,cond)]    

print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


##### Exemplo recomendado - Uso do WHERE

In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

yarr = np.array([2.1,2.2,2.3,2.4,2.5])

cond = np.array([True,False,True,True,False])

# Com base nos valores booleanos do array COND é definido o resultado sem a necessidade LOOPS
result = np.where(cond,xarr,yarr)

print(result)

[1.1 2.2 1.3 1.4 2.5]


##### Exemplo - Uso do WHERE com valores ESCALARES

In [ ]:
# Neste exemplo iremos aplicar um valor ESCALAR baseado em uma CONDICIONAL

arr = rng.standard_normal((4,4))

print(f"Array origem:\n{arr}")

result = np.where(arr > 0 ,2,-2)

print(f"\nArray alterado com where:\n{result}")



# Filtro com where
result = np.where(arr > 0)
arr[result]

Array origem:
[[ 0.06114402  0.0709146   0.43365454  0.27748366]
 [ 0.53025239  0.53672097  0.61835001 -0.79501746]
 [ 0.30003095 -1.60270159  0.26679883 -1.26162378]
 [-0.07127081  0.47404973 -0.41485376  0.0977165 ]]

Array alterado com where:
(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3, 3], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 0, 2, 1, 3], dtype=int64))


array([0.06114402, 0.0709146 , 0.43365454, 0.27748366, 0.53025239,
       0.53672097, 0.61835001, 0.30003095, 0.26679883, 0.47404973,
       0.0977165 ])

### DTYPE OBJECT

Apesar de um array NUMPY ser HOMOGÊNEO, e aceitar apenas um tipo de dado, quando definimos o DTYPE com o OBJECT o array suporta a MESCLA de vários tipos

In [13]:
arr_object = np.array(["0",1,2,3.5,"paulo"],dtype=object)

print(arr_object)
print(arr_object.dtype)

['0' 1 2 3.5 'paulo']
object
